// client-react/src/components/table/table.tsx
import React, { FC } from "react";
import { Card as CardObj } from "../../../../scopone-rx-service/src/model/card";
import { PlayerState } from "../../../../scopone-rx-service/src/model/player";
import { Team } from "../../../../scopone-rx-service/src/model/team";
import { Card } from "../card/card";

import "./table.css";

interface ITableProps {
  teams: [Team, Team];
  currentPlayerName: string;
  cards: CardObj[];
}

export const Table: FC<ITableProps> = ({ teams, currentPlayerName, cards }) => {
  const playerName = (tNum: number, pNum: number) => {
    let name = teams[tNum].Players[pNum] ? teams[tNum].Players[pNum].name : "-";
    name = playerLeft(tNum, pNum) ? `${name} (left the Osteria)` : name;
    name = isCurrentPlayer(tNum, pNum) ? `${name} (can play card)` : name;
    return name;
  };
  const playerLeft = (tNum: number, pNum: number) => {
    return teams && teams[tNum].Players[pNum]
      ? teams[tNum].Players[pNum].status === PlayerState.playerLeftTheGame
      : false;
  };
  const isCurrentPlayer = (tNum: number, pNum: number) => {
    return teams && teams[tNum].Players[pNum]
      ? teams[tNum].Players[pNum].name === currentPlayerName
      : false;
  };
  const marginLeft = (i: number) => {
    return `${i * 12}%`;
  };

  return (
    <>
      <div className="main">
        <div className="table">
          <div className="board">
            <table className="players-table">
              <tbody>
                <tr className="table-row">
                  <td></td>
                  <td>
                    <div
                      className={`player player-3 ${
                        playerLeft(1, 0) ? "player-absent" : ""
                      } ${isCurrentPlayer(1, 0) ? "current-player" : ""}`}
                    >
                      {playerName(1, 0)}
                    </div>
                  </td>
                  <td></td>
                </tr>
                <tr className="table-row">
                  <td>
                    <div
                      className={`player player-1 ${
                        playerLeft(0, 0) ? "player-absent" : ""
                      } ${isCurrentPlayer(0, 0) ? "current-player" : ""}`}
                    >
                      {playerName(0, 0)}
                    </div>
                  </td>
                  <td></td>
                  <td>
                    <div
                      className={`player player-2 ${
                        playerLeft(0, 1) ? "player-absent" : ""
                      } ${isCurrentPlayer(0, 1) ? "current-player" : ""}`}
                    >
                      {playerName(0, 1)}
                    </div>
                  </td>
                </tr>
                <tr className="table-row">
                  <td></td>
                  <td>
                    <div
                      className={`player player-4 ${
                        playerLeft(1, 1) ? "player-absent" : ""
                      } ${isCurrentPlayer(1, 1) ? "current-player" : ""}`}
                    >
                      {playerName(1, 1)}
                    </div>
                  </td>
                  <td></td>
                </tr>
              </tbody>
            </table>
            {cards?.map((card, i) => (
              <Card
                card={card}
                style={{ marginLeft: marginLeft(i) }}
                height="100"
                key={`${card.suit}${card.type}`}
              ></Card>
            ))}
          </div>
        </div>
      </div>
    </>
  );
};

// client-ng/src/app/components/table/table.component.ts
import {
  Component,
  OnInit,
  Input,
  ChangeDetectionStrategy,
} from '@angular/core';
import { Card } from '../../../../../scopone-rx-service/src/model/card';
import { PlayerState } from '../../../../../scopone-rx-service/src/model/player';
import { Team } from '../../../../../scopone-rx-service/src/model/team';

@Component({
  selector: 'scopone-table',
  templateUrl: './table.component.html',
  styleUrls: ['./table.component.css'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class TableComponent implements OnInit {
  @Input() teams: [Team, Team];
  @Input() public currentPlayerName: string;
  @Input() public cards: Card[];

  constructor() {}

  ngOnInit(): void {}

  playerName(tNum: number, pNum: number) {
    let name = this.teams
      ? this.teams[tNum].Players[pNum]
        ? this.teams[tNum].Players[pNum].name
        : '-'
      : '';
    name = this.playerLeft(tNum, pNum) ? `${name} (left the Osteria)` : name;
    name = this.isCurrentPlayer(tNum, pNum) ? `${name} (can play card)` : name;
    return name;
  }
  playerLeft(tNum: number, pNum: number) {
    return this.teams && this.teams[tNum].Players[pNum]
      ? this.teams[tNum].Players[pNum].status === PlayerState.playerLeftTheGame
      : false;
  }
  isCurrentPlayer(tNum: number, pNum: number) {
    return this.teams && this.teams[tNum].Players[pNum]
      ? this.teams[tNum].Players[pNum].name === this.currentPlayerName
      : false;
  }
  marginLeft(i: number) {
    return `${i * 12}%`;
  }
}

<!-- Inspired by https://codepen.io/goodo73/pen/wbtug -->
<div class="main">
  <div class="table">
    <div class="board">
      <table class="players-table">
        <tr class="table-row">
          <td></td>
          <td>
            <div
              class="player player-3"
              [class.player-absent]="playerLeft(1, 0)"
              [class.current-player]="isCurrentPlayer(1, 0)"
            >
              {{ playerName(1, 0) }}
            </div>
          </td>
          <td></td>
        </tr>
        <tr class="table-row">
          <td>
            <div
              class="player player-1"
              [class.player-absent]="playerLeft(0, 0)"
              [class.current-player]="isCurrentPlayer(0, 0)"
            >
              {{ playerName(0, 0) }}
            </div>
          </td>
          <td></td>
          <td>
            <div
              class="player player-2"
              [class.player-absent]="playerLeft(0, 1)"
              [class.current-player]="isCurrentPlayer(0, 1)"
            >
              {{ playerName(0, 1) }}
            </div>
          </td>
        </tr>
        <tr class="table-row">
          <td></td>
          <td
            class="player player-4"
            [class.player-absent]="playerLeft(1, 1)"
            [class.current-player]="isCurrentPlayer(1, 1)"
          >
            <div>{{ playerName(1, 1) }}</div>
          </td>
          <td></td>
        </tr>
      </table>

      <div *ngFor="let card of cards; index as i">
        <scopone-card
          [card]="card"
          class="card"
          [style.margin-left]="marginLeft(i)"
        >
        </scopone-card>
      </div>
    </div>
  </div>
</div>
