// client-react/src/components/card/card.tsx
import { FC } from "react";
import "./card.css";

import {
  Card as PlayingCard,
  Suits,
  Types,
} from "../../../../scopone-rx-service/src/card";

enum TypesView {
  Ace = "1",
  King = "k",
  Queen = "q",
  Jack = "j",
  Seven = "7",
  Six = "6",
  Five = "5",
  Four = "4",
  Three = "3",
  Two = "2",
}
const suitsMap = new Map<Suits, string>();
suitsMap.set(Suits.BASTONI, "c");
suitsMap.set(Suits.COPPE, "h");
suitsMap.set(Suits.DENARI, "d");
suitsMap.set(Suits.SPADE, "s");

interface ICardProps {
  card: PlayingCard;
  style?: any;
  height: string;
  clickHandler?: (card: PlayingCard) => void;
}

export const Card: FC<ICardProps> = (props) => {
  const cardSvg = (suit: Suits, type: Types) => {
    const t = TypesView[type];
    const s = suitsMap.get(suit);
    const resourcePath = `/card-images/svg/${t}${s}.svg`;
    // https://create-react-app.dev/docs/using-the-public-folder#when-to-use-the-public-folder
    return process.env.PUBLIC_URL + resourcePath;
  };

  return (
    <img
      style={props.style}
      height={props.height}
      className="playing-card"
      src={cardSvg(props.card.suit, props.card.type)}
      alt={`${props.card.type} ${props.card.suit}`}
      onClick={() => props.clickHandler(props.card)}
    />
  );
};

// client-ng/src/app/components/card/card.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';
import { Card, Types, Suits } from '../../../../../scopone-rx-service/src/card';

const trevigianeSuitsMap = new Map<Suits, string>();
trevigianeSuitsMap[Suits.BASTONI] = 'B';
trevigianeSuitsMap[Suits.COPPE] = 'C';
trevigianeSuitsMap[Suits.DENARI] = 'D';
trevigianeSuitsMap[Suits.SPADE] = 'S';
@Component({
  selector: 'scopone-card',
  templateUrl: './card.component.html',
  styleUrls: ['./card.component.scss'],
})
export class CardComponent {
  @Input() public card: Card;
  @Output() public cardClicked = new EventEmitter<Card>();
  bastoni = Suits.BASTONI;
  spade = Suits.SPADE;

  constructor() {}

  type() {
    enum TypeViews {
      Ace = 'A',
      King = 'K',
      Queen = 'Q',
      Jack = 'J',
      Seven = '7',
      Six = '6',
      Five = '5',
      Four = '4',
      Three = '3',
      Two = '2',
    }
    return TypeViews[this.card.type];
  }

  trevigianeType() {
    enum TrevigianeTypeMap {
      Ace = 'Asso',
      King = 'Re',
      Queen = 'Cavallo',
      Jack = 'Fante',
      Seven = '7',
      Six = '6',
      Five = '5',
      Four = '4',
      Three = '3',
      Two = '2',
    }
    return TrevigianeTypeMap[this.card.type];
  }
  trevigianeSuite() {
    return trevigianeSuitsMap[this.card.suit];
  }

  trevigianeImageUrl() {
    return `./assets/Cartetrevisane/${this.trevigianeSuite()} ${this.trevigianeType()}.jpg`;
  }

  click() {
    this.cardClicked.emit(this.card);
  }
}
