// client-ng/src/app/components/hand-result/hand-result.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';

import { ScoponeService } from '../../scopone/scopone.service';
import { MatDialog } from '@angular/material/dialog';
import { CloseGameDialogueComponent } from './close-game-dialogue.component';
import { Observable } from 'rxjs';
import { PlayerView } from '../../../../../scopone-rx-service/src/model/player-view';
import { map, share, tap } from 'rxjs/operators';
import { Card } from '../../../../../scopone-rx-service/src/model/card';

@Component({
  selector: 'scopone-hand-result',
  templateUrl: './hand-result.component.html',
  styleUrls: ['./hand-result.component.css'],
})
export class HandResultComponent implements OnInit {
  finalHandView$: Observable<PlayerView>;
  finalHandScore$: Observable<string>;
  gameScore$: Observable<string>;
  ourCards$: Observable<Card[]>;
  theirCards$: Observable<Card[]>;
  ourScope$: Observable<Card[]>;
  theirScope$: Observable<Card[]>;

  constructor(
    public scoponeService: ScoponeService,
    private router: Router,
    public dialog: MatDialog
  ) {}

  ngOnInit(): void {
    this.finalHandView$ = this.scoponeService.handClosed_ShareReplay$;

    this.finalHandScore$ = this.finalHandView$.pipe(
      map(
        (finalHandView) =>
          `Hand score: "Us" ${finalHandView.ourFinalScore} - "Them" ${finalHandView.theirFinalScore}`
      )
    );

    this.gameScore$ = this.finalHandView$.pipe(
      map(
        (finalHandView) =>
          `Game score: "Us" ${finalHandView.ourCurrentGameScore} - "Them" ${finalHandView.theirCurrentGameScore}`
      )
    );

    this.ourCards$ = this.finalHandView$.pipe(
      map((finalHandView) => finalHandView.ourScorecard.carte)
    );

    this.theirCards$ = this.finalHandView$.pipe(
      map((finalHandView) => finalHandView.theirScorecard.carte)
    );

    this.ourScope$ = this.finalHandView$.pipe(
      map((finalHandView) => finalHandView.ourScope)
    );

    this.theirScope$ = this.finalHandView$.pipe(
      map((finalHandView) => finalHandView.theirScope)
    );
  }

  continue() {
    this.scoponeService.newHand();
    this.router.navigate(['hand']);
  }
  close() {
    const dialogRef = this.dialog.open(CloseGameDialogueComponent, {
      width: '400px',
      height: '200px',
    });
    dialogRef.afterClosed().subscribe((terminate) => {
      if (terminate) {
        this.scoponeService.closeCurrentGame();
        // the navigation to the 'bye' page is governed by the GameComponent so that, when a game is closed by one player,
        // all players are automatically brought to the 'bye' page and not only the player who has actualle closed the game
        // this.router.navigate(['bye']);
      }
    });
  }
}

<mat-card>
  <mat-card-title>
    {{ finalHandScore$ | async }}
  </mat-card-title>
  <mat-card-subtitle> {{ gameScore$ | async }}</mat-card-subtitle>
  <mat-card-content>
    <scopone-cards [cards]="ourCards$ | async" name="Our Cards"></scopone-cards>
    <scopone-cards
      [cards]="theirCards$ | async"
      name="Their Cards"
    ></scopone-cards>
    <scopone-cards [cards]="ourScope$ | async" name="Our Scope"></scopone-cards>
    <scopone-cards
      [cards]="theirScope$ | async"
      name="Their Scope"
    ></scopone-cards>
  </mat-card-content>
  <mat-card-actions>
    <button mat-button (click)="continue()">Continue</button>
    <button mat-button (click)="close()" *ngIf="!scoponeService.observing">
      Terminate
    </button>
  </mat-card-actions>
</mat-card>

// client-react/src/components/hand-result/hand-result.tsx
import React, { FC, useContext, useEffect, useState } from "react";
import {
  Button,
  Card,
  CardContent,
  CardHeader,
  DialogActions,
} from "@material-ui/core";

import { ServerContext } from "../../context/server-context";
import { Card as CardObj } from "../../../../scopone-rx-service/src/model/card";
import { Cards } from "../cards/cards";
import { tap } from "rxjs/operators";
import { useHistory } from "react-router-dom";
import { TerminateDialogue } from "./terminate-game-dialogue";

// we define a type for the state so that we can issue a single call to the update state function and
// avoid so multiple execution of the render function
// https://stackoverflow.com/questions/53574614/multiple-calls-to-state-updater-from-usestate-in-component-causes-multiple-re-re
type HandResultState = {
  finalHandScore: string;
  gameScore: string;
  ourCards: CardObj[];
  theirCards: CardObj[];
  ourScope: CardObj[];
  theirScope: CardObj[];
  observing: boolean;
};
export type TerminateGameState = {
  handleTerminateGame: () => void;
  handleCancel: () => void;
};

export const HandResult: FC = () => {
  const server = useContext(ServerContext);
  const history = useHistory();

  const [handResultState, setHandResultState] = useState<HandResultState>();

  const [terminateGameState, setTerminateGameState] =
    useState<TerminateGameState>();

  useEffect(() => {
    console.log("=======>>>>>>>>>>>>  Use Effect run in HandResult");

    const finalHandView$ = server.handClosed_ShareReplay$.pipe(
      tap((finalHandView) => {
        const finalHandScore = `Hand score: "Us" ${finalHandView.ourFinalScore} - "Them" ${finalHandView.theirFinalScore}`;
        const gameScore = `Game score: "Us" ${finalHandView.ourCurrentGameScore} - "Them" ${finalHandView.theirCurrentGameScore}`;
        setHandResultState({
          finalHandScore,
          gameScore,
          ourCards: finalHandView.ourScorecard.carte,
          theirCards: finalHandView.theirScorecard.carte,
          ourScope: finalHandView.ourScope,
          theirScope: finalHandView.theirScope,
          observing: server.observing,
        });
      })
    );

    const subscription = finalHandView$.subscribe();

    return () => {
      console.log("Unsubscribe HandResult subscription");
      subscription.unsubscribe();
    };
  }, [server]);

  const handleContinue = () => {
    server.newHand();
    history.push("/hand");
  };
  const handleTerminateGame = () => {
    const handleTerminateGame = () => {
      server.closeCurrentGame();
    };
    const handleCancel = () => {
      setTerminateGameState(null);
    };
    setTerminateGameState({
      handleTerminateGame,
      handleCancel,
    });
  };
  const handleViewHistory = () => {
    history.push("/hand-history");
  };

  return (
    <>
      {handResultState && (
        <Card className="root" variant="outlined">
          <CardHeader
            title={handResultState.finalHandScore}
            className="header"
          ></CardHeader>
          <CardHeader
            title={handResultState.gameScore}
            className="header"
          ></CardHeader>
          <CardContent>
            <Cards
              cards={handResultState.ourCards}
              name="Our cards"
              layout="spread-left"
            ></Cards>
            <Cards
              cards={handResultState.ourScope}
              name="Our scope"
              layout="spread-left"
            ></Cards>
            <Cards
              cards={handResultState.theirCards}
              name="Their cards"
              layout="spread-left"
            ></Cards>
            <Cards
              cards={handResultState.theirScope}
              name="Their scope"
              layout="spread-left"
            ></Cards>
          </CardContent>
          <DialogActions>
            <Button onClick={handleContinue} color="primary">
              Continue
            </Button>
            {!handResultState.observing && (
              <Button onClick={handleTerminateGame} color="primary" autoFocus>
                Terminate Game
              </Button>
            )}
            <Button onClick={handleViewHistory} color="primary" autoFocus>
              View History
            </Button>
          </DialogActions>
        </Card>
      )}
      {terminateGameState && (
        <TerminateDialogue {...terminateGameState}></TerminateDialogue>
      )}
    </>
  );
};
