// client-react/src/components/game-list/game-list.tsx
import { List, ListItem, ListItemText } from "@material-ui/core";
import React, { useContext, useEffect, useState } from "react";
import { combineLatest } from "rxjs";
import { map } from "rxjs/operators";
import { ServerContext } from "../../context/server-context";
import { Game } from "../../scopone-rx-service/messages";

type GameForList = Game & { canBeObservedOnly: boolean };

export const GameList = () => {
  const [games, setGames] = useState<Array<GameForList>>([]);
  const [selectedIndex, setSelectedIndex] = useState<number>();
  const server = useContext(ServerContext);

  useEffect(() => {
    console.log(
      "=======<<<<<<<<<<<<<<<>>>>>>>>>>>>  Use Effect run in GameList"
    );
    const subscription = combineLatest([
      server.gamesNotYetStarted$,
      server.gamesWhichCanBeObserved$,
    ])
      .pipe(
        map(([gNotStarted, gObservable]) => {
          const gamesNotStarted = gNotStarted.map(
            (g) => ({ ...g, canBeObservedOnly: false } as GameForList)
          );
          const gamesObservable = gObservable.map(
            (g) => ({ ...g, canBeObservedOnly: true } as GameForList)
          );
          return [...gamesNotStarted, ...gamesObservable];
        })
      )
      .subscribe({
        next: setGames,
      });
    return () => subscription.unsubscribe();
  }, [server]);

  const gameName = (game: GameForList) => {
    return game.canBeObservedOnly ? `${game.name} (as an Observer)` : game.name;
  };

  const handleListItemClick = (
    event: React.MouseEvent<HTMLDivElement, MouseEvent>,
    index: number
  ) => {
    setSelectedIndex(index);
  };

  return (
    <div className="root">
      <List component="nav">
        {games.map((game, i) => (
          <ListItem
            // className={game.canBeObservedOnly ? "observableOnly" : ""}
            key={game.name}
            button
            selected={selectedIndex === i}
            onClick={(event) => handleListItemClick(event, i)}
          >
            <ListItemText
              primary={gameName(game)}
              className="observableOnly"
              primaryTypographyProps={
                game.canBeObservedOnly
                  ? {
                      style: {
                        color: "red",
                      },
                    }
                  : {}
              }
            />
          </ListItem>
        ))}
      </List>
    </div>
  );
};

// client-ng/src/app/components/game-list/game-list.component.ts
import { Component, OnInit } from '@angular/core';
import { Observable, zip } from 'rxjs';
import { Game } from '../../../../../scopone-rx-service/src/messages';
import { ScoponeServerService } from '../../../../../scopone-rx-service/src/scopone-server.service';
import { MatDialog } from '@angular/material/dialog';
import { MatListOption } from '@angular/material/list';
import { GamePickerDialogueComponent } from './game-picker-dialogue.component';
import { map } from 'rxjs/operators';

@Component({
  selector: 'scopone-game-list',
  templateUrl: './game-list.component.html',
  styleUrls: ['./game-list.component.css'],
})
export class GameListComponent implements OnInit {
  games$: Observable<Game[]>;
  gamesNotStarted: string[];
  gamesObservable: string[];

  constructor(
    public scoponeServer: ScoponeServerService,
    public dialog: MatDialog
  ) {}

  ngOnInit(): void {
    this.games$ = zip(
      this.scoponeServer.gamesNotYetStarted$,
      this.scoponeServer.gamesWhichCanBeObserved$
    ).pipe(
      map(([gNotStarted, gObservable]) => {
        this.gamesNotStarted = gNotStarted.map((g) => g.name);
        this.gamesObservable = gObservable.map((g) => g.name);
        return [...gNotStarted, ...gObservable];
      })
    );
  }

  gameSelected(options: MatListOption[]) {
    const game = options[0].value;
    const dialogRef = this.dialog.open(GamePickerDialogueComponent, {
      width: '400px',
      height: '150px',
      data: { game },
    });
    dialogRef.afterClosed().subscribe((OK) => {
      if (OK) {
        if (this.isGameObservable(game)) {
          this.scoponeServer.addObserverToGame(
            this.scoponeServer.playerName,
            game.name
          );
        } else {
          this.scoponeServer.addPlayerToGame(
            this.scoponeServer.playerName,
            game.name
          );
        }
      } else {
        options[0].selected = false;
      }
    });
  }
  isGameObservable(game: Game) {
    return this.gamesObservable.includes(game.name);
  }
  gameName(game: Game) {
    return this.isGameObservable(game)
      ? `${game.name} (as an Observer)`
      : game.name;
  }
}
